### PR TITLE
Show number of total calls in the selected range

### PR DESCRIPTION
**Pull request by iszulcdeepsense**
I hope it makes more sense now:

Screenshot from 2023-01-20 17-13-11

### CODE REVIEW

**Comment by JosefAssadERST** [comment]
~~Ah, is this live anywhere?~~ Ah never mind, I see it's live on C3 dev. Yeah I think this is more useful than what it replaces. @nielshelsoe agree?

**Comment by nielshelsoe** [comment]
Jah I think so. 
Just so I get it. The old counter was just the total of all endpoints called in a Fatman? (E.g. labels,health, perform e.c.t.)

**Comment by JosefAssadERST** [comment]
> Jah I think so. Just so I get it. The old counter was just the total of all endpoints called in a Fatman? (E.g. labels,health, perform e.c.t.)

Yeah.

Old: show total since the Big Bang

New: respect the time range selected on the dashboard up here:

billede

**Review by JosefAssadERST — APPROVED** [review]
LGTM

**Pull request merged**
