### PR TITLE
Rename Fatman to Job in database models

### PR DESCRIPTION
**Pull request by iszulcdeepsense**

### CODE REVIEW

**Comment by LookACastle** [comment]
[This image](https://github.com/TheRacetrack/racetrack/blob/2c6e4b5dcecf660c5ac4da6a8bcea493c8b6b44e/docs/assets/dashboard-meowmeow.jpg) is changed, but not degreased. It still says fatman.

**Comment by iszulcdeepsense** [comment]
> [This image](https://github.com/TheRacetrack/racetrack/blob/2c6e4b5dcecf660c5ac4da6a8bcea493c8b6b44e/docs/assets/dashboard-meowmeow.jpg) is changed, but not degreased. It still says fatman.

@LookACastle  What do you mean? `dashboard-meowmeow.jpg` has been removed in this Pull Request and it's replaced by https://github.com/TheRacetrack/racetrack/blob/92d89c601f6e63356c9207a1cdd3e5121059b88a/docs/assets/dashboard-example.png

**Comment by LookACastle** [comment]
The github UI confused me, you are right.

**Review by LookACastle — APPROVED** [review]
If you want to make sure the issue is completely done, might as well fix all the images. `./docs/assets/permission-add.png`, `./docs/assets/job-type-plugins.png`, `./docs/assets/example-curl-call.png`, and `./docs/assets/racetrack-components.drawio.png`.

If you think that makes more sense as a separate pull request, LGTM.

**Pull request merged**
